server:
  port: 9999
spring:
  application:
    name: spring-cloud-config-server
  #配置连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/554262411/spring-cloud-config.git
          order: 1
          username: 554262411
          password: fengdl19871126
          #启动时下载到本地
          #force-pull: true
      name: config-server

