server:
  port: 8888

#Eureka配置
eureka:
  client:
    service-url:
      #注册地址，使用逗号分隔可以配置多个
      defaultZone: http://localhost:9001/eureka/
      ##如果是向注册中心的一个集群进行注册
      ##那我们只需要向其中的任意一台注册中心注册即可
      ##该注册中心会把请求转发集群内的其他注册中心，（服务同步）
  instance:
    #修改eureka上默认描述信息！
    instance-id: zuul-8888
    #设置为true时，当鼠标移动到实例名称上时，显示的是IP信息，为false信息时显示为主机名信息
    prefer-ip-address: true

#配置监控提示信息
info:
  app.name: ${spring.application.name}
  company.name: fundaylei

#spring配置
spring:
  application:
    name: zuul

#zuul配置
zuul:
  routes:
    #服务名称
    provider.serviceId: PROVIDER01
    #服务映射，隐藏真实服务名称，使用path替换
    provider.path: /api-provider/**
    #服务名称
    consumer.serviceId: COMSUMER01
    #服务映射，隐藏真实服务名称，使用path替换
    consumer.path: /api-consumer/**

  #忽略掉使用服务名称访问，设置后使用服务无法访问
  #'*'  使用‘*’可忽略掉所有服务
  ignored-services: PROVIDER01,COMSUMER01
  #忽略掉所有包含/admin/的路径
  #ignored-patterns: /**/admin/**
